---------------- ######################################### Basket_data first layer ####################################################### ----------------------------
"RECORD_CONTENT":"basket_additional_charge"."additional_charge_price"."gross" AS BASKET_ADDITIONAL_CHARGE_ADDITIONAL_CHARGE_PRICE_GROSS
, "RECORD_CONTENT":"basket_additional_charge"."additional_charge_price"."net" AS BASKET_ADDITIONAL_CHARGE_ADDITIONAL_CHARGE_PRICE_NET
, "RECORD_CONTENT":"basket_additional_charge"."additional_charge_price"."tax" AS BASKET_ADDITIONAL_CHARGE_ADDITIONAL_CHARGE_PRICE_TAX
, "RECORD_CONTENT":"basket_additional_charge"."additional_charge_price"."tax_rate" AS BASKET_ADDITIONAL_CHARGE_ADDITIONAL_CHARGE_PRICE_TAX_RATE
, "RECORD_CONTENT":"basket_additional_charge"."type" AS BASKET_ADDITIONAL_CHARGE_TYPE
, "RECORD_CONTENT":"basket_discount"."gross" AS BASKET_DISCOUNT_GROSS
, "RECORD_CONTENT":"basket_discount"."net" AS BASKET_DISCOUNT_NET
, "RECORD_CONTENT":"basket_discount"."tax" AS BASKET_DISCOUNT_TAX
, "RECORD_CONTENT":"basket_discount"."tax_rate" AS BASKET_DISCOUNT_TAX_RATE
, "RECORD_CONTENT":"basket_source_name" AS BASKET_SOURCE_NAME
, "RECORD_CONTENT":"basket_source_original_id" AS BASKET_SOURCE_ORIGINAL_ID
, "RECORD_CONTENT":"created_at" AS CREATED_AT
, "RECORD_CONTENT":"currency" AS CURRENCY
, "RECORD_CONTENT":"line_items" AS LINE_ITEMS
, "RECORD_CONTENT":"salt_consumer_id" AS SALT_CONSUMER_ID
, "RECORD_CONTENT":"salt_merchant_employee_id" AS SALT_MERCHANT_EMPLOYEE_ID
, "RECORD_CONTENT":"salt_payment_transaction_id" AS SALT_PAYMENT_TRANSACTION_ID
, "RECORD_CONTENT":"salt_store_id" AS SALT_STORE_ID
, "RECORD_CONTENT":"status" AS STATUS
, "RECORD_CONTENT":"total_to_pay"."gross" AS TOTAL_TO_PAY_GROSS
, "RECORD_CONTENT":"total_to_pay"."net" AS TOTAL_TO_PAY_NET
, "RECORD_CONTENT":"total_to_pay"."tax" AS TOTAL_TO_PAY_TAX
, "RECORD_CONTENT":"total_to_pay"."tax_rate" AS TOTAL_TO_PAY_TAX_RATE
, "RECORD_CONTENT":"updated_at" AS UPDATED_AT
, "RECORD_METADATA":"CreateTime" AS RECORD_METADATA_CREATETIME
, "RECORD_METADATA":"key"."schema_key" AS RECORD_METADATA_KEY_SCHEMA_KEY
, "RECORD_METADATA":"key"."service_access_id" AS RECORD_METADATA_KEY_SERVICE_ACCESS_ID
, "RECORD_METADATA":"key"."timestamp" AS RECORD_METADATA_KEY_TIMESTAMP
, "RECORD_METADATA":"offset" AS RECORD_METADATA_OFFSET
, "RECORD_METADATA":"partition" AS RECORD_METADATA_PARTITION
, "RECORD_METADATA":"topic" AS RECORD_METADATA_TOPIC

----------------- ######################################## Line_items ################################################################ ------------------------------
, "RECORD_CONTENT":"line_items".[0]."gtin" AS LINE_ITEMS_0_GTIN
, "RECORD_CONTENT":"line_items".[0]."id" AS LINE_ITEMS_0_ID
, "RECORD_CONTENT":"line_items".[0]."line_attributes"."name" AS LINE_ITEMS_0_LINE_ATTRIBUTES_NAME
, "RECORD_CONTENT":"line_items".[0]."line_attributes"."value" AS LINE_ITEMS_0_LINE_ATTRIBUTES_VALUE
, "RECORD_CONTENT":"line_items".[0]."line_discounts"."gross" AS LINE_ITEMS_0_LINE_DISCOUNTS_GROSS
, "RECORD_CONTENT":"line_items".[0]."line_discounts"."net" AS LINE_ITEMS_0_LINE_DISCOUNTS_NET
, "RECORD_CONTENT":"line_items".[0]."line_discounts"."tax" AS LINE_ITEMS_0_LINE_DISCOUNTS_TAX
, "RECORD_CONTENT":"line_items".[0]."line_discounts"."tax_rate" AS LINE_ITEMS_0_LINE_DISCOUNTS_TAX_RATE
, "RECORD_CONTENT":"line_items".[0]."line_price"."gross" AS LINE_ITEMS_0_LINE_PRICE_GROSS
, "RECORD_CONTENT":"line_items".[0]."line_price"."net" AS LINE_ITEMS_0_LINE_PRICE_NET
, "RECORD_CONTENT":"line_items".[0]."line_price"."tax" AS LINE_ITEMS_0_LINE_PRICE_TAX
, "RECORD_CONTENT":"line_items".[0]."line_price"."tax_rate" AS LINE_ITEMS_0_LINE_PRICE_TAX_RATE
, "RECORD_CONTENT":"line_items".[0]."name" AS LINE_ITEMS_0_NAME
, "RECORD_CONTENT":"line_items".[0]."quantity" AS LINE_ITEMS_0_QUANTITY
, "RECORD_CONTENT":"line_items".[0]."quantity_unit" AS LINE_ITEMS_0_QUANTITY_UNIT
, "RECORD_CONTENT":"salt_consumer_id" AS SALT_CONSUMER_ID
