RECORD_CONTENT:"after"."created_at" AS CREATED_AT
, RECORD_CONTENT:"after"."id" AS  ID
, RECORD_CONTENT:"after"."mode" AS MODE
, RECORD_CONTENT:"after"."pipeline_full_name" AS PIPELINE_FULL_NAME
, RECORD_CONTENT:"after"."target_id" AS TARGET_ID
, RECORD_CONTENT:"before" AS BEFORE_CONTENT
, RECORD_CONTENT:"op" AS OP
, RECORD_CONTENT:"source"."connector " AS SOURCE_CONNECTOR
, RECORD_CONTENT:"source"."db" AS SOURCE_DB
, RECORD_CONTENT:"source "."lsn" AS SOURCE_LSN
, RECORD_CONTENT:"source"."name" AS SOURCE_NAME
, RECORD_CONTENT:"so urce"."schema" AS SOURCE_SCHEMA
, RECORD_CONTENT:"source"."sequence" AS SOURCE_SEQUENCE
, RECORD_CONTENT:"source"."snapshot" AS SOURCE_SNAPSHOT
, RECORD_CONTENT:"source"."table" AS SO URCE_TABLE
, RECORD_CONTENT:"source"."ts_ms" AS SOURCE_TS_MS
, RECORD_CONTENT:"source"."txId" AS SOURCE_TXID
, RECORD_CONTENT:"source"."version" AS SOURCE_VERSION
, RECORD_CONTENT:"source"."xmin" AS SOURCE_XMIN
, RECORD_CONTENT:"transaction" AS TRANSACTION
, RECORD_CONTENT:"ts_ms" AS TS_MS
